export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS'
export const SELECTED_PROJECT = 'SELECTED_PROJECT'

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS'
export const SELECTED_TASK = 'SELECTED_TASK'